import type { ModeFlow, SimulationMode, StepDefinition } from './types';

export const MODE_LABELS: Record<SimulationMode, { title: string; subtitle: string }> = {
  none: { title: '無保護機制', subtitle: 'Race Condition / Double Booking' },
  setnx: { title: 'Redis 基礎鎖', subtitle: 'SETNX + TTL' },
  lua: { title: '終極方案', subtitle: 'Lua Script 原子操作 + 暫扣過期' },
};

export const SWIM_LANES = [
  { id: 'user', title: '使用者介面', subtitle: 'User' },
  { id: 'api', title: '後端服務', subtitle: 'API Server' },
  { id: 'redis', title: 'Redis', subtitle: 'Cache' },
  { id: 'db', title: 'Database', subtitle: 'Persistent Storage' },
] as const;

export const MODE_FLOWS: Record<SimulationMode, ModeFlow> = {
  none: {
    nodes: [
      {
        id: 'user-select',
        lane: 'user',
        x: 40,
        kind: 'step',
        number: 1,
        icon: 'user',
        title: '選擇座位 A1',
        subtitle: '2 位使用者同時送出訂位請求',
      },
      {
        id: 'api-query',
        lane: 'api',
        x: 240,
        kind: 'step',
        number: 2,
        icon: 'server',
        title: '直接查詢座位',
        subtitle: '未使用任何鎖定機制',
      },
      {
        id: 'db-write',
        lane: 'db',
        x: 440,
        kind: 'step',
        number: 3,
        icon: 'db',
        title: '各自寫入售出',
        subtitle: "UPDATE seats SET status='sold'",
      },
      {
        id: 'outcome-fail',
        lane: 'user',
        x: 640,
        kind: 'outcome',
        icon: 'x',
        title: '❌ Overbooking Detected',
        subtitle: '多筆請求同時售出同一座位',
        tone: 'fail',
      },
    ],
    edges: [
      { id: 'user-select__api-query', source: 'user-select', target: 'api-query', tone: 'neutral' },
      { id: 'api-query__db-write', source: 'api-query', target: 'db-write', tone: 'neutral' },
      { id: 'db-write__outcome-fail', source: 'db-write', target: 'outcome-fail', tone: 'fail' },
    ],
  },
  setnx: {
    nodes: [
      {
        id: 'user-select',
        lane: 'user',
        x: 40,
        kind: 'step',
        number: 1,
        icon: 'user',
        title: '選擇座位 A1',
        subtitle: '2 位使用者同時送出訂位請求',
      },
      {
        id: 'api-request',
        lane: 'api',
        x: 240,
        kind: 'step',
        number: 2,
        icon: 'server',
        title: '請求保留座位',
        subtitle: '呼叫保留座位 API',
      },
      {
        id: 'redis-lock',
        lane: 'redis',
        x: 440,
        kind: 'step',
        number: 3,
        icon: 'redis',
        title: '搶奪 Redis 鎖',
        subtitle: 'SET lock:seat:A1 <reqId> NX EX 10',
      },
      { id: 'decision', lane: 'redis', x: 650, kind: 'decision', title: '取得鎖？', subtitle: '' },
      {
        id: 'outcome-fail',
        lane: 'user',
        x: 860,
        kind: 'outcome',
        icon: 'x',
        title: '🛑 Lock Acquisition Failed',
        subtitle: '請稍後再試或選擇其他座位',
        tone: 'fail',
      },
      {
        id: 'db-write',
        lane: 'db',
        x: 860,
        kind: 'step',
        number: 5,
        icon: 'db',
        title: '寫入訂單',
        subtitle: "UPDATE seats SET status='sold'",
      },
      {
        id: 'api-complete',
        lane: 'api',
        x: 1000,
        kind: 'step',
        number: 6,
        icon: 'server',
        title: '完成訂位',
        subtitle: '回傳訂位成功',
      },
      {
        id: 'outcome-success',
        lane: 'user',
        x: 1180,
        kind: 'outcome',
        icon: 'check',
        title: '✅ 座位售出成功',
        subtitle: '唯一贏家完成購票',
        tone: 'success',
      },
    ],
    edges: [
      { id: 'user-select__api-request', source: 'user-select', target: 'api-request', tone: 'neutral' },
      { id: 'api-request__redis-lock', source: 'api-request', target: 'redis-lock', tone: 'neutral' },
      { id: 'redis-lock__decision', source: 'redis-lock', target: 'decision', tone: 'neutral' },
      { id: 'decision__outcome-fail', source: 'decision', target: 'outcome-fail', label: '否', tone: 'fail' },
      { id: 'decision__db-write', source: 'decision', target: 'db-write', label: '是', tone: 'success' },
      { id: 'db-write__api-complete', source: 'db-write', target: 'api-complete', tone: 'neutral' },
      { id: 'api-complete__outcome-success', source: 'api-complete', target: 'outcome-success', tone: 'success' },
    ],
  },
  lua: {
    nodes: [
      {
        id: 'user-select',
        lane: 'user',
        x: 40,
        kind: 'step',
        number: 1,
        icon: 'user',
        title: '選擇座位 A1',
        subtitle: '2 位使用者同時送出訂位請求',
      },
      {
        id: 'api-request',
        lane: 'api',
        x: 240,
        kind: 'step',
        number: 2,
        icon: 'server',
        title: '請求保留座位',
        subtitle: '呼叫保留座位 API',
      },
      {
        id: 'redis-lock',
        lane: 'redis',
        x: 440,
        kind: 'step',
        number: 3,
        icon: 'redis',
        title: '執行原子 Lua Script',
        subtitle: 'EVAL atomic_lock_and_hold.lua',
      },
      { id: 'decision', lane: 'redis', x: 650, kind: 'decision', title: '原子操作\n成功？', subtitle: '' },
      {
        id: 'outcome-fail',
        lane: 'user',
        x: 860,
        kind: 'outcome',
        icon: 'x',
        title: '🛑 Lock Acquisition Failed',
        subtitle: '請稍後再試或選擇其他座位',
        tone: 'fail',
      },
      {
        id: 'db-write',
        lane: 'db',
        x: 860,
        kind: 'step',
        number: 5,
        icon: 'db',
        title: '建立待付款訂單',
        subtitle: 'INSERT pending order, TTL=10s',
      },
      {
        id: 'api-complete',
        lane: 'api',
        x: 1000,
        kind: 'step',
        number: 6,
        icon: 'server',
        title: '建立暫扣',
        subtitle: '回傳暫扣中，請於期限內付款',
      },
      {
        id: 'outcome-success',
        lane: 'user',
        x: 1180,
        kind: 'outcome',
        icon: 'check',
        title: '🟡 座位暫扣中',
        subtitle: '10 秒倒數，逾時自動釋放',
        tone: 'pending',
      },
    ],
    edges: [
      { id: 'user-select__api-request', source: 'user-select', target: 'api-request', tone: 'neutral' },
      { id: 'api-request__redis-lock', source: 'api-request', target: 'redis-lock', tone: 'neutral' },
      { id: 'redis-lock__decision', source: 'redis-lock', target: 'decision', tone: 'neutral' },
      { id: 'decision__outcome-fail', source: 'decision', target: 'outcome-fail', label: '否', tone: 'fail' },
      { id: 'decision__db-write', source: 'decision', target: 'db-write', label: '是', tone: 'success' },
      { id: 'db-write__api-complete', source: 'db-write', target: 'api-complete', tone: 'neutral' },
      { id: 'api-complete__outcome-success', source: 'api-complete', target: 'outcome-success', tone: 'success' },
    ],
  },
};

export const STEP_DEFINITIONS: Record<SimulationMode, StepDefinition[]> = {
  none: [
    {
      title: '併發請求進入',
      description: '2 個使用者同時對座位 A1 送出購票請求，請求抵達 API Gateway。',
      activeNodeIds: ['user-select'],
      activeEdgeIds: [],
    },
    {
      title: '各自直接讀取座位狀態',
      description: '每個請求各自查詢資料庫，沒有任何鎖定機制，全部都讀到「可購買」。',
      activeNodeIds: ['user-select', 'api-query'],
      activeEdgeIds: ['user-select__api-query'],
    },
    {
      title: '各自寫入售出',
      description: '由於沒有原子性保護，所有請求都各自把座位標記為已售出，造成超賣。',
      activeNodeIds: ['user-select', 'api-query', 'db-write', 'outcome-fail'],
      activeEdgeIds: ['user-select__api-query', 'api-query__db-write', 'db-write__outcome-fail'],
    },
  ],
  setnx: [
    {
      title: '併發請求進入',
      description: '2 個使用者同時對座位 A1 送出購票請求，請求抵達 API Server。',
      activeNodeIds: ['user-select', 'api-request'],
      activeEdgeIds: ['user-select__api-request'],
    },
    {
      title: '搶奪 Redis 鎖',
      description: '每個請求對 Redis 執行 SET lock:seat:A1 <reqId> NX EX 10，搶第一個成功者。',
      activeNodeIds: ['user-select', 'api-request', 'redis-lock', 'decision'],
      activeEdgeIds: ['user-select__api-request', 'api-request__redis-lock', 'redis-lock__decision'],
    },
    {
      title: '唯一贏家寫入訂單',
      description: '只有取得鎖的請求能繼續寫入資料庫，其餘請求立即收到鎖定失敗。',
      activeNodeIds: [
        'user-select',
        'api-request',
        'redis-lock',
        'decision',
        'outcome-fail',
        'db-write',
        'api-complete',
        'outcome-success',
      ],
      activeEdgeIds: [
        'user-select__api-request',
        'api-request__redis-lock',
        'redis-lock__decision',
        'decision__outcome-fail',
        'decision__db-write',
        'db-write__api-complete',
        'api-complete__outcome-success',
      ],
    },
  ],
  lua: [
    {
      title: '併發請求進入',
      description: '2 個使用者同時對座位 A1 送出購票請求，請求抵達 API Server。',
      activeNodeIds: ['user-select', 'api-request'],
      activeEdgeIds: ['user-select__api-request'],
    },
    {
      title: '執行原子 Lua Script',
      description: '透過 EVAL 在 Redis 端一次完成「檢查 + 鎖定」，確保操作不可分割。',
      activeNodeIds: ['user-select', 'api-request', 'redis-lock', 'decision'],
      activeEdgeIds: ['user-select__api-request', 'api-request__redis-lock', 'redis-lock__decision'],
    },
    {
      title: '建立暫扣訂單並倒數',
      description: '贏家寫入待付款訂單，座位進入 10 秒暫扣倒數，逾時未付款將自動釋放。',
      activeNodeIds: [
        'user-select',
        'api-request',
        'redis-lock',
        'decision',
        'outcome-fail',
        'db-write',
        'api-complete',
        'outcome-success',
      ],
      activeEdgeIds: [
        'user-select__api-request',
        'api-request__redis-lock',
        'redis-lock__decision',
        'decision__outcome-fail',
        'decision__db-write',
        'db-write__api-complete',
        'api-complete__outcome-success',
      ],
    },
  ],
};

export const HOLD_TTL_SECONDS = 10;
export const THREAD_COUNT = 2;
